server:
  port: 8091

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 10.1.1.50:8848
        username: nacos_test1
        password: nacos_test1
        group: DEFAULT_GROUP
        namespace: 855c0a8b-ec4e-412c-a81f-dd4ff9c19cb1

